export const AUTHORIZATION_REASON_CODES = {
  ALLOWED: "ALLOWED",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  IDENTITY_INACTIVE: "IDENTITY_INACTIVE",
  CERTIFICATION_INACTIVE: "CERTIFICATION_INACTIVE",
  ORGANIZATION_MEMBERSHIP_INACTIVE: "ORGANIZATION_MEMBERSHIP_INACTIVE",
  PROJECT_MEMBERSHIP_INACTIVE: "PROJECT_MEMBERSHIP_INACTIVE",
  STAFF_POSITION_INACTIVE: "STAFF_POSITION_INACTIVE",
  CAPABILITY_MISSING: "CAPABILITY_MISSING",
  DATA_SCOPE_MISMATCH: "DATA_SCOPE_MISMATCH",
  RESOURCE_RELATION_REQUIRED: "RESOURCE_RELATION_REQUIRED",
  RESOURCE_STATE_FORBIDDEN: "RESOURCE_STATE_FORBIDDEN",
  CONFIDENTIALITY_TOO_HIGH: "CONFIDENTIALITY_TOO_HIGH",
  NDA_REQUIRED: "NDA_REQUIRED",
  GRANT_INACTIVE: "GRANT_INACTIVE",
  SEPARATION_OF_DUTIES: "SEPARATION_OF_DUTIES",
  SELF_APPROVAL_FORBIDDEN: "SELF_APPROVAL_FORBIDDEN",
  FIELD_ACCESS_DENIED: "FIELD_ACCESS_DENIED",
  CONCURRENT_MODIFICATION: "CONCURRENT_MODIFICATION",
} as const;

export type AuthorizationReasonCode = typeof AUTHORIZATION_REASON_CODES[keyof typeof AUTHORIZATION_REASON_CODES];

export const DENY_REASON_CODES = Object.values(AUTHORIZATION_REASON_CODES).filter(
  (code): code is Exclude<AuthorizationReasonCode, "ALLOWED"> => code !== "ALLOWED",
);
